name: Publish Release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: Install cyrillic package
        run: |
        sudo apt-get update
        sudo apt-get install -y texlive-lang-cyrillic
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cvFullYehorKozyr.tex
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          artifacts: "cvFullYehorKozyr.pdf"
          generateReleaseNotes: true
          makeLatest: true
